### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by gieljnssns** [maddox/itunes-api#14]
I can't figure out how to install this.
Can someone please explain.

**Comment by maddox** [comment]
Run `script/setup` - https://github.com/maddox/itunes-api#setup

Then run `script/install` - https://github.com/maddox/itunes-api#install-as-service-on-os-x

**Comment by gieljnssns** [comment]
when i download the zip and then run script/bootstrap , i get this
`Last login: Wed Feb 17 14:04:15 on ttys000
/Users/Giel/Downloads/itunes-api-master/script/bootstrap ; exit;
MacBook:~ Giel$ /Users/Giel/Downloads/itunes-api-master/script/bootstrap ; exit;
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path /Users/Giel/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/Users/Giel/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Giel/npm-debug.log
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`
And when i run script/install , get
`Last login: Wed Feb 17 16:01:27 on ttys000
MacBook:~ Giel$ /Users/Giel/Downloads/itunes-api-master/script/install ; exit;
Installing itunes-api...
cp: config/org.itunes-api.plist: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`

**Comment by maddox** [comment]
you need to be in the actual directory to run the scripts. Then it'll find the `package.json`and install the correct dependencies. Try that and then run `script/restart` so it uninstalls and reinstalls as a service.

**Comment by gieljnssns** [comment]
iMac-5k:itunes-api-master Giel$ sudo npm install forever -g

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
 
> fsevents@1.0.7 install /usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
/usr/local/bin/forever -> /usr/local/lib/node_modules/forever/bin/forever
forever@0.15.1 /usr/local/lib/node_modules/forever
├── path-is-absolute@1.0.0
├── object-assign@3.0.0
├── colors@0.6.2
├── clone@1.0.2
├── timespan@2.3.0
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── prettyjson@1.1.3 (colors@1.1.2, minimist@1.2.0)
├── winston@0.8.3 (cycle@1.0.3, async@0.2.10, eyes@0.1.8, stack-trace@0.0.9, isstream@0.1.2, pkginfo@0.3.1)
├── nconf@0.6.9 (ini@1.3.4, async@0.2.9, optimist@0.6.0)
├── nssocket@0.5.3 (eventemitter2@0.4.14, lazy@1.0.11)
├── shush@1.0.0 (strip-json-comments@0.1.3, caller@0.0.1)
├── utile@0.2.1 (async@0.2.10, deep-equal@1.0.1, i@0.3.4, ncp@0.4.2, mkdirp@0.5.1, rimraf@2.5.2)
├── flatiron@0.4.3 (director@1.2.7, optimist@0.6.0, prompt@0.2.14, broadway@0.3.6)
└── forever-monitor@1.6.0 (minimatch@2.0.10, broadway@0.3.6, chokidar@1.4.2, ps-tree@0.0.3)
iMac-5k:itunes-api-master Giel$ /Users/Giel/Documents/itunes-api-master/script/bootstrap 
parameterize@0.0.7 node_modules/parameterize

osa@2.2.0 node_modules/osa

morgan@1.6.1 node_modules/morgan
├── basic-auth@1.0.3
├── on-headers@1.0.1
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
└── debug@2.2.0 (ms@0.7.1)

body-parser@1.15.0 node_modules/body-parser
├── content-type@1.0.1
├── bytes@2.2.0
├── depd@1.1.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── qs@6.1.0
├── debug@2.2.0 (ms@0.7.1)
├── raw-body@2.1.5 (unpipe@1.0.0)
├── http-errors@1.4.0 (inherits@2.0.1, statuses@1.2.1)
├── iconv-lite@0.4.13
└── type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)

express@4.13.4 node_modules/express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── content-type@1.0.1
├── cookie-signature@1.0.6
├── vary@1.0.1
├── methods@1.1.2
├── merge-descriptors@1.0.1
├── range-parser@1.0.3
├── content-disposition@0.5.1
├── fresh@0.3.0
├── parseurl@1.3.1
├── cookie@0.1.5
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── serve-static@1.10.2
├── depd@1.1.0
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── send@0.13.1 (destroy@1.0.4, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.10)
└── type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)

local-itunes@0.3.0 node_modules/local-itunes
├── neo-async@1.7.2
├── require-dir@0.3.0
└── osascript@1.2.0 (duplex-child-process@0.0.5)
Finished setting up itunes-api! run it with script/server or install it with script/install.
iMac-5k:itunes-api-master Giel$ /Users/Giel/Documents/itunes-api-master/script/install 
Installing itunes-api...
/Users/Giel/Library/LaunchAgents/org.itunes-api.plist: Invalid or missing Program/ProgramArguments
iMac-5k:itunes-api-master Giel$ /Users/Giel/Documents/itunes-api-master/script/restart 
Uninstalling itunes-api...
/Users/Giel/Library/LaunchAgents/org.itunes-api.plist: Could not find specified service
Installing itunes-api...
/Users/Giel/Library/LaunchAgents/org.itunes-api.plist: Invalid or missing Program/ProgramArguments

**Comment by maddox** [comment]
Ah,  know what this is! Let me push up a change.

**Comment by maddox** [comment]
Oh, actually, the thing that I thought was preventing this from happening actually IS happening. I thought you were missing the directory that the `launchd` script is installed to. But `script/install` is creating the directory. 

could you run this to see if the `launchd` script is in the right place?

```
cat /Users/Giel/Library/LaunchAgents/org.itunes-api.plist
```

**Comment by gieljnssns** [comment]
iMac-5k:itunes-api-master Giel$ cat /Users/Giel/Library/LaunchAgents/org.itunes-api.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>org.itunes-api</string>

    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/local/bin/:/usr/bin:$PATH</string>
      <key>NODE_ENV</key>
      <string>production</string>
    </dict>

    <key>Program</key>
    <string>script/server</string>

    <key>AbandonProcessGroup</key>
    <false/>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>

    <key>WorkingDirectory</key>
    <string>/Users/Giel/documents/itunes-api-master</string>

    <key>StandardErrorPath</key>
    <string>/Users/Giel/Library/Logs/itunes-api.log</string>

    <key>StandardOutPath</key>
    <string>/Users/Giel/Library/Logs/itunes-api.log</string>

  </dict>
</plist>

**Comment by maddox** [comment]
I just changed the `Program` key's value to be the full path. Pull down the most current code and try doing this again and see if it helps it.

**Comment by gieljnssns** [comment]
Now it works, but i can't quit iTunes anymore.
When I close it, it reopens immediately.

**Comment by maddox** [comment]
> Now it works

Great!

> but i can't quit iTunes anymore.
When I close it, it reopens immediately.

Yes, because `itunes-api` is continually polling iTunes state for what's currently playing, via AppleScript. When AppleScript is excited on an application, it automatically launches.

`itunes-api` simply can't even work the way it's intended without iTunes always open, so this isn't any sort of unwanted behavior. If you want to close iTunes, uninstall `itunes-api` with `script/uninstall`.

**Comment by gieljnssns** [comment]
Thanks, but i have 3 more questions,
How do  i set a specific playlist to play?
<img width="360" alt="schermafbeelding 2016-02-17 om 18 19 24" src="https://cloud.githubusercontent.com/assets/17234951/13118225/976d608a-d5a3-11e5-9bb3-84092210421f.png">

Where is "Computer" as endpoint?
<img width="323" alt="schermafbeelding 2016-02-17 om 18 24 13" src="https://cloud.githubusercontent.com/assets/17234951/13118269/c4f73594-d5a3-11e5-93cf-bd1b488121de.png">

And at last, is it possible to start and end itunes-api together with iTunes?

Giel

**Comment by gieljnssns** [comment]
I use home assistant.

**Comment by maddox** [comment]
> I use home assistant.

Yah, no problem. I wrote all the integrations for this so I'm familiar.

> Where is "Computer" as endpoint?

Computer isn't actually exposed as a speaker, because it's not an AirPlay endpoint. I'll look into seeing what it will take to make that work.

> How do i set a specific playlist to play?

Here's an example of a scene that sets the media player to play a specific playlist by name. `Cooking` in this config, is a playlist named "Cooking".

```yaml
- name: Cooking Time
  entities:
    media_player.kitchen_music_airtunes_speaker: on
    media_player.itunes:
      state: playing
      media_type: playlist
      media_id: Cooking
```

**Comment by gieljnssns** [comment]
Thanks a lot!

**Comment by drinksomewhiskey** [comment]
For some reason I am still confused after reading this thread. Do I download the files separately or is there a zip file to download what I need? Also, do I need to use terminal to install this? Is there a step by step write up guide?
