### ISSUE TITLE
[Feature Request] Love/Like currently playing song

### ISSUE THREAD

**Issue by cemolcay** [maddox/itunes-api#20]
Hi, thanks for the api!!
Is it possible to add like/love songs in apple music playlists and stations?
  
![itunes](https://cloud.githubusercontent.com/assets/2419578/17307996/a01a7008-57ec-11e6-9c11-575b44eaa591.png)

**Comment by maddox** [comment]
Probably not. The API doesn't even work while playing from Apple Music
things. Only actual playlists in your library.
