### ISSUE TITLE
Avoid iTunes to auto start

### ISSUE THREAD

**Issue by benquan** [maddox/itunes-api#27]
Is there a way to avoid iTunes to autostart every time? If the api is running iTunes is always running. If I close it, iTunes-api opens it again! Can it only open iTunes if you actually want to play something?

Thanks!

**Comment by maddox** [comment]
The API talks directly to iTunes over AppleScript. It can't function without iTunes open.

**Comment by Joshfindit** [comment]
to @benquan's request, I would like the following:

- If iTunes is open, itunes-api works as expected
- If iTunes is closed, itunes-api goes in to 'dormant mode', possibly simply ignoring commands or opening iTunes *when* a media event is called (play, etc)

I'm cool with iTunes needing to be open for itunes-api, I just don't want iTunes open all the time.
