### ISSUE TITLE
Errors on non standard node installs like nvm

### ISSUE THREAD

**Issue by thibmaek** [maddox/itunes-api#29]
`script/server: line 9: /usr/local/bin/forever: No such file or directory` after a bootstrap because not everyone's node install and binaries live at /usr/local/bin/.

The simplest fix for this is to call forever in the shell scripts with `$(which forever)`. I changed it locally, and output works with this fix.

![image](https://user-images.githubusercontent.com/6213695/29042437-2d41e6e8-7bb7-11e7-95c7-b68e718fd1c1.png)

**Comment by chieft8** [comment]
I am getting this same error even tho see forever in usr/local/bin
