### ISSUE TITLE
Can run Install script

### ISSUE THREAD

**Issue by VdkaShaker** [maddox/itunes-api#37]
I open the Install script and get:

```
/Applications/itunes-api-master/script/install ; exit;
Installing itunes-api...
cp: config/org.itunes-api.plist: No such file or directory
logout
```
`org.itunes-api.plist` is in the `config` folder

Any suggestions?

**Comment by auditdata** [comment]
Is this api still supported and working. I have the same issue as above.

**Comment by maddox** [comment]
where are you running the script from? Are you at the root of the project directory?

**Comment by auditdata** [comment]
No from the script directory?

**Comment by maddox** [comment]
Nope. 

`script/install`

**Comment by auditdata** [comment]
Thanks Jon. 
Now done that and itunes is open.
Is there a way to test it?
I have the component in Home Assistant and it says offline.
I have the correct IP of the MacBook running iTunes
Do I need to run any other script other than install?
Sorry to be a pain but I am excited about this.
:-)
Clive

**Comment by maddox** [comment]
It should just be running. You can hit it with some `curl` commands to test out the http API. In terms of home assistant, it should show any airplay speakers on your network. If you start iTunes playing, it should show what's playing, and let you pause/resume things. As for more, I can't really remember, I use Sonos now, heh.

**Comment by auditdata** [comment]
Thanks all working now
:-)
Clive
